# Default values for golang-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ealmeidaneto/web
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "golang-web"
fullnameOverride: "golang-web-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "golang-web"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer : "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: golang.ealmeidaneto.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: golang-web-tls
     hosts:
       - golang.ealmeidaneto.net

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80

tolerations: []

affinity: {}
